name: hffix test

# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches:
      - master
  pull_request:
  # release:
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test:
    runs-on:
      - ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - cxx: "g++"
        # https://stackoverflow.com/questions/76859275/error-compiling-a-cpp-containing-stdchrono-errorstatic-constexpr-unsigned-fra
        - cxx: "clang++ -stdlib=libc++"
        flags:
        - cxxflags: "-std=c++98"
        - cxxflags: "-std=c++11"
        - cxxflags: "-std=c++17"
        - cxxflags: "-std=c++20"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.5
        id:   install-boost
        with:
          boost_version: 1.83.0
      - name: Test
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        shell: bash
        env:
          CPLUS_INCLUDE_PATH: ${{steps.install-boost.outputs.BOOST_ROOT}}/include
          LIBRARY_PATH: ${{steps.install-boost.outputs.BOOST_ROOT}}/lib
          CXX: ${{matrix.compiler.cxx}}
          CXXFLAGS: ${{matrix.flags.cxxflags}}
        run: |
           $CXX --version
           make test
